version: "3.8"

services:
  hackathon:
    container_name: hackathon
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: hackathon
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  hackathon:
    name: hackathon